variables:
  FORCE_COLOR: 1
  APP_NAME: 'web-ideal-architecture'
  FRONT_APP: 'true'

default:
  image: 930600874599.dkr.ecr.eu-west-3.amazonaws.com/tech/docker-images/node:18-112-ci
  before_script:
    - corepack enable
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

stages:
  - build
  - test
  - deploy
  - pages

build:
  stage: build
  script: NEXT_TELEMETRY_DISABLED=1 pnpm run build
  variables:
    PRODUCTION: 'true'
  artifacts:
    expire_in: 30 mins
    paths:
      - apps/workshop/storybook-static
      - apps/auth/out

pages:
  stage: pages
  needs: ['build']
  script:
    - rm -rf public/
    - mkdir public/
    - mv apps/auth/out public/auth
    - mv apps/workshop/storybook-static public/storybook
    
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always

lint:
  needs: []
  timeout: 20m
  script: NEXT_TELEMETRY_DISABLED=1 pnpm run lint

test:
  image: mcr.microsoft.com/playwright:v1.37.0-jammy
  stage: test
  needs: []
  timeout: 20m
  script: pnpm run test
  artifacts:
    expire_in: 1h
    reports:
      junit: 'apps/**/.playwright/report/junit.xml'
      coverage_report:
        coverage_format: cobertura
        path: 'apps/qonto-js/.playwright/monocart/coverage/cobertura-coverage.xml'
    paths:
      - 'apps/**/.playwright/'

test-components:
  image: mcr.microsoft.com/playwright:v1.37.0-jammy
  stage: test
  needs: []
  timeout: 20m
  script: pnpm run test-ct
  artifacts:
    expire_in: 1h
    reports:
      junit: 'apps/**/.playwright/report/ct-junit.xml'

deploy-storybook:
  stage: deploy
  needs: ["build"]
  when: manual
  dependencies:
    - "build"
  script: npx chromatic --project-token=$CHROMATIC_TOKEN --exit-zero-on-changes -d apps/workshop/storybook-static